### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#103]
Let's have a conversation about this, whether it is American or International date format. But regardless, the "th" and "rd" need to be taken down in SP map, and cases and situations. Yet, let's do have a conversation about which format, because I see merits in both ways.

**Comment by budparr** [comment]
I think I missed it on the map when we made the [last](https://github.com/ABA-Center-for-Human-Rights/aba-icc/issues/101) change, but where is it on Cases & Situations?

**Comment by kiphale** [comment]
In the Key Events and Facts and Allegations section.

Example http://www.aba-icc.org/cases/case/the-prosecutor-v-bemba-et-al/

But I honestly do want your opinion on date format. I go both ways on it.

**Comment by budparr** [comment]
just where it says "last updated" right?

**Comment by kiphale** [comment]
![image](https://cloud.githubusercontent.com/assets/8195536/13674614/31cf7230-e6ac-11e5-8e7f-1d851da1d78a.png)

**Comment by kiphale** [comment]
Look at the date format of key events. It is replicated throughout the website that way.

**Comment by budparr** [comment]
Ah, I see. No problem to change. I don't think the format matters as much as the consistency. I'll fix these.

**Comment by kiphale** [comment]
My thoughts are that we are an American organization speaking primarily to an American audience, we should keep it in American format. But maybe there is something to be said for our international audience. Thoughts?

**Comment by budparr** [comment]
My rule: When in doubt, look what the NYTimes does. Perhaps in this case, the Economist would be a better guide?

**Comment by kiphale** [comment]
Well not entirely sure if looking at American style guide answers the question!

**Comment by budparr** [comment]
The Economist is a UK publication with an Int'l audience. Financial Times too.

**Comment by kiphale** [comment]
It is an UK publication?!? Learn something new everyday.

**Comment by kiphale** [comment]
Ok. Well I have decided then: American style: January 1, 2016 --> no th or 3rd --> no abbreviated months either. Thanks!

**Comment by budparr** [comment]
Funny, I thought American style include nth/nd/rd. 

Here's the economist style guide (which I'm not necessarily recommending) http://www.economist.com/style-guide/dates

**Comment by kiphale** [comment]
Yes, I saw their style guide, but the th and 3rd make me cringe. I pulled out my trusty Bluebook, and it says no th and rd. Looks cleaner.

**Comment by budparr** [comment]
Spec:
- Month: full month, "January" not "Jan"
- Day of month - leading zeros: none,  "1" not "01"
- Ordinal suffix (nth): exclude
- Year: four digits,  "2016" not "16"
