### ISSUE TITLE
Timeline not loading!

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#104]
!!!!

https://www.aba-icc.org/the-aba-icc-project/aba-policy-on-the-icc/

**Comment by budparr** [comment]
Might just be something from Knightlab that's not loading (a server down on their end). I'll monitor.

**Comment by budparr** [comment]
it's working fine. Where did you get that link from? the right link is 

`http://www.aba-icc.org/the-aba-icc-project/aba-policy-on-the-icc/`

Note the difference? ` http:// ` vs ` https:// `

Can't serve mixed content on a page.

**Comment by kiphale** [comment]
That link came up on a google search! Problem me thinks

**Comment by budparr** [comment]
what were the search terms?

**Comment by kiphale** [comment]
ABA Urge Syria referral ICC

**Comment by budparr** [comment]
Okay. I'll see if I can submit something to Google to change those. Not sure why they're coming up that way.

**Comment by kiphale** [comment]
Ok thanks!

**Comment by budparr** [comment]
This is now fixed, as is the potential issue with for search engines to come to the https link (now the entire site is served over https, which is a good thing)
