### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#105]
http://www.aba-icc.org/about-the-icc/situations-cases/

And for some reasons Austria pops up below too.

**Comment by budparr** [comment]
ok weird. Am I going crazy? Why do we have the map on two separate pages?

**Comment by budparr** [comment]
duh. figured it out. Somehow Austria got some content in it and showed up on the page, and that, because it didn't really have content, screwed up the page. I'll see if I can fix it so that sort of thing won't happen.
