### ISSUE TITLE
Review Home page

### ISSUE THREAD

**Issue by budparr** [ABA-Center-for-Human-Rights/aba-icc#106]
Hey, @kiphale I thought I'd tweak the home page a bit as I migrated the software back to the old platform. 

Here's what I did:
- Improve size and gutter (white bars around the boxes) to look more "modern."
- Lighten up some of the colors.
- Mix up some of the headings to link to more items.
- Encourage scrolling to see news below the grid (by having some of the content slide below the viewable area and make the lower grid items brighter to draw attention).
- Added Last three news posts below grid.

The rest of the site still needs a couple of things, but for this release I also updated the map code, so it's a bit smoother.

Please review the home page and let me know if you approve.
http://staging-aba-icc.sonnetmedia.com/

We should be ready to launch the new version on Monday, at which point I'll get back to the other things on my list.

**Comment by budparr** [comment]
Screen shot. Some older versions of Internet Explorer may not look like this.
<img width="1440" alt="screen shot 2016-03-25 at 2 55 06 pm" src="https://cloud.githubusercontent.com/assets/115347/14051495/d2a4f9e8-f299-11e5-8b40-2b27e45fd044.png">

**Comment by kiphale** [comment]
![image](https://cloud.githubusercontent.com/assets/8195536/14053312/c0b66df4-f2a6-11e5-81e8-60085df428f9.png)

**Comment by kiphale** [comment]
From my desktop

**Comment by kiphale** [comment]
![image](https://cloud.githubusercontent.com/assets/8195536/14053335/e556d2de-f2a6-11e5-978e-7ba91608e01f.png)

Desktop from Explorer
