### ISSUE TITLE
Short Description under Key Events - Top of that Section

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#108]
2.	There is information or description of events under Case events which shows at the bottom of the page on the website, is it possible for it to be on top of the key events, the way it was before.

**Comment by budparr** [comment]
could you drop an example link on these, por favor?

**Comment by kiphale** [comment]
Expand key events and the short 1-2 sentence summary is at the bottom of Key Events, not top like it use to be. https://www.aba-icc.org/cases/case/the-prosecutor-v-ruto-and-sang/

**Comment by budparr** [comment]
got it, thanks for the details.
