### ISSUE TITLE
Event Recap

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#112]
So I noticed when we create event recaps in ABA-ICC.org, the hyperlink to the title of the event opens a new tab back to that same event recap splash page. Can we make it that if you click on the title, it takes you to the ICJT event recap?

**Comment by budparr** [comment]
Actually, we should just remove the hyperlink from the title (expected behavior would take you to more details— on the existing site—it's just that we don't have more details on them), so as to not be confusing.
