### ISSUE TITLE
U.S.-ICC 

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#121]
please change U.S. to US 

https://www.aba-icc.org/about-the-icc/the-us-icc-relationship/  - on the sidebar too

**Comment by kiphale** [comment]
This also exists in one of the panels on ICJT, specifically on one discussing Ipsos polling results.

**Comment by budparr** [comment]
Isn't this in your copy? Not seeing where it would be coded.

**Comment by kiphale** [comment]
Precisely. Because it is not in our copy, I cannot change. I made a change on the timeline (I think) but I do not think I can for the ICTJ one.

**Comment by budparr** [comment]
I think we're misunderstanding one another. I ONLY see U.S. in your copy (in the timeline), but nowhere else.

**Comment by budparr** [comment]
On the ICJT page I use "U.S." throughout the copy.

**Comment by kiphale** [comment]
Don't worry about the timeline. 

See here that the panels on Ipsos polling scrolling at the top says "U.S" and "I.C.C." 
https://www.international-criminal-justice-today.org/ 

Should not have periods.

**Comment by budparr** [comment]
Right. That one's an image. I'll fix that. What about the others?

**Comment by kiphale** [comment]
In the intervening time since starting this issue, I fixed some and will do the others, so no worries.

**Comment by budparr** [comment]
Oh, okay. Just wanted to make sure I wasn't missing something. I'll take care of the image.
