### ISSUE TITLE
Cases tab is not syncing with people tab.

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#85]
When you click the cases tab, the people and their pictures are not lining up with the description of the person and their case. I tried to sort the two tabs so they lined up the same but that did not seem to change it. (For instance, the picture of Gaddafi lines up with the description of Laurent Gbagbo)

**Comment by budparr** [comment]
Let me know if this problem still exists. I'm not seeing it, but send me a link if you can.
