### ISSUE TITLE
External Links

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#89]
@budparr Get lots of request to be listed on our website, which we do not have a section for. Let us please create a section for this, depending on where we think is best. 

The first to go on the list, and so I dont forget is OSJI Justice Monitor. http://www.ijmonitor.org/

**Comment by budparr** [comment]
so do you want a stand-alone page for them?

**Comment by kiphale** [comment]
Well, it depends. Our discussions on the new format/structure of the website has hit upon making the design better for navigation, so maybe it won't need a "stand-alone page" as presently constituted. But, to answer your question, maybe it could be added to "Contact" to be "Contact and External Links" or just added to "About the Project" at the end?

**Comment by budparr** [comment]
the structure of the website hasn't really changed. It's just more "solid" now. Maybe I'll just push out the new version. It's not quite done yet (some work still on S&C), but it should be fine and at least we can add links and that other change you want to make without having to duplicate on the old and the new.

**Comment by budparr** [comment]
the structure of the website hasn't really changed. It's just more "solid" now. Maybe I'll just push out the new version. It's not quite done yet (some work still on S&C), but it should be fine and at least we can add links and that other change you want to make without having to duplicate on the old and the new.

**Comment by budparr** [comment]
the structure of the website hasn't really changed. It's just more "solid" now. Maybe I'll just push out the new version. It's not quite done yet (some work still on S&C), but it should be fine and at least we can add links and that other change you want to make without having to duplicate on the old and the new.

**Comment by kiphale** [comment]
Thanks. I get the more "solid" part, but I do also recall you wanting to make design changes (to a certain extent). Regardless, I am not wedded to any one way/section to put the external links. I simply wanted to time with what you are doing. No rush!

**Comment by budparr** [comment]
I'll just put it up - you know me, build and iterate!

**Comment by kiphale** [comment]
What is this "build and iterate" thing you speak of? I have never heard such words combined in this way before. ;)

**Comment by budparr** [comment]
emoji smile

**Comment by kiphale** [comment]
Just re-raising this issue.
