### ISSUE TITLE
Anchors for Rome Statute reference

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#90]
@budparr If we do need to hyperlink to the Rome Statute and pinpoint with an anchor to a specific provision, this website rocks! http://www.iclklamberg.com/Statute.htm#_ftnref1071

**Comment by budparr** [comment]
added it to the wiki
https://github.com/ABA-Center-for-Human-Rights/aba-icc/wiki/Resources
