### ISSUE TITLE
News linking

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#92]
@budparr The previous problem with events not linking to ICTJ properly, news is not linking to ICTJ once in the news you clicked on. It actually is not showing anything at all.  http://www.aba-icc.org/news/senator-durbins-speech-highlights-aba-working-group-on-crimes-against-humanity/

It does not look like the events either. http://www.aba-icc.org/events/

**Comment by budparr** [comment]
I'm closing this because I think it's solved, but feel free to open again if needed.
