### ISSUE TITLE
Image?

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#94]
@budparr Can I play around with the default image that is used on this website? The one that graces the top banner on most pages?

**Comment by budparr** [comment]
Sure. what sort of thing do you want there? I left it as neutral as possible, but do you want something with color?

**Comment by kiphale** [comment]
I don't know...I was just gonna play around with images. But yes, I was thinking color. Or would that be too much?

**Comment by budparr** [comment]
the reason I don't have color is it's impossible to predict what's going to go there. what do you think would look good on this page? http://www.aba-icc.org/board-of-advisors/hon-thomas-buergenthal/

**Comment by kiphale** [comment]
You're right. As usual...hence, why I asked the "source"!

**Comment by budparr** [comment]
but you're right that it's not the greatest image though

**Comment by kiphale** [comment]
how can we find something better?

**Comment by budparr** [comment]
dunno. not seen anything better

**Comment by kiphale** [comment]
Let's (you and me) figure this one out.

**Comment by budparr** [comment]
I think you find an appropriate image (meaningful, but general) and I'll doctor it up so that it blends nicely.

**Comment by kiphale** [comment]
Deal
