### ISSUE TITLE
Situation and Cases map hyperlinks

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#95]
On the S&C map, there are hyperlinks below the country's description that come up when you click on an individual country. Kip would like if you could remove the links to the ICC labeled "source" and capitalize "country page".

**Comment by budparr** [comment]
Is Kip speaking in the third person now?

**Comment by kiphale** [comment]
When was Kip not speaking in the third person?

**Comment by budparr** [comment]
the royal kip
