### ISSUE TITLE
Mohammed Hussein Ali

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#96]
@budparr This accused was accidentally deleted and we cannot recreate a profile for him as the CMS still thinks he exists (it thinks we're creating a duplicate accused page).

**Comment by budparr** [comment]
it probably just needed a bit of time to update. I just created a draft entry for you. 

I thought I didn't give the interns the ability to delete things. Was it deleted using your account?
