### ISSUE TITLE
Flags?

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#98]
@budparr Maybe in the Situations and Cases Overview there could be flags next to names of countries? Something to spruce it up!

**Comment by budparr** [comment]
Are there any issues with countries thatIn are in dispute?

**Comment by kiphale** [comment]
Meaning are there any countries that are disputed countries? Other than Palestine (which has a undisputed flag), no. 

 

Christopher “Kip” Hale

Senior Counsel 

American Bar Association Center for Human Rights

Tel.: (202) 662-1584

E-mail: kip.hale@americanbar.org 

Websites: www.aba-icc.org <http://www.aba-icc.org/>  & 

                     www.international-criminal-justice-today.org <http://www.international-criminal-justice-today.org/>  

Facebook: facebook.com/ABAICCProject <https://www.facebook.com/ABAICCProject> 

Twitter: @abaiccproject <https://twitter.com/ABAICCProject> 

 

 

 

This electronic message contains information from the American Bar Association.  The contents may be privileged and confidential and are intended for the use of the intended addressee(s) only.  If you are not an intended addressee, note that any disclosure, copying, distribution, or use of the contents of this message is prohibited.  If you have received this e-mail in error, please contact me at kip.hale@americanbar.org.

**Comment by budparr** [comment]
Okay. My thinking was to avoid any sort of nationalistic viewpoint, but if it's no big deal we can do flags. My little country shapes didn't work out all that well (though maybe the need to be bigger)

**Comment by kiphale** [comment]
Well I don’t think putting a flag up is necessarily nationalistic in this context. Let me think about it first some more…maybe it gives off the connotation that the country is under investigation rather than crimes within it. 

 

Christopher “Kip” Hale

Senior Counsel 

American Bar Association Center for Human Rights

Tel.: (202) 662-1584

E-mail: kip.hale@americanbar.org 

Websites: www.aba-icc.org <http://www.aba-icc.org/>  & 

                     www.international-criminal-justice-today.org <http://www.international-criminal-justice-today.org/>  

Facebook: facebook.com/ABAICCProject <https://www.facebook.com/ABAICCProject> 

Twitter: @abaiccproject <https://twitter.com/ABAICCProject> 

 

 

 

This electronic message contains information from the American Bar Association.  The contents may be privileged and confidential and are intended for the use of the intended addressee(s) only.  If you are not an intended addressee, note that any disclosure, copying, distribution, or use of the contents of this message is prohibited.  If you have received this e-mail in error, please contact me at kip.hale@americanbar.org.
